/* Set the Apps Script deployment URL after deploying apps-script/Code.gs. */
const GAS_URL = "https://script.google.com/macros/s/AKfycbyhPN_YBVpTp_fKne4BAlxIkyBA9wtT3QjIFkAsi-ZxX6m69IkUlw3KeRgzfG-xy6-vbQ/exec";
const JATA_URL = "https://i.ibb.co/fYY58Rh2/JATA-NEGARA-PNG.png";
const FORM_TYPES = {
  umum: { title: "OPR Umum", description: "Laporan program lengkap dengan objektif, kekuatan dan penambahbaikan.", fields: [
    ["tajukProgram", "Tajuk Program / Aktiviti *", "text", "Contoh: Program…", true], ["tarikhPelaksanaan", "Tarikh / Tempoh Pelaksanaan *", "text", "Contoh: 12 Ogos 2026", true], ["masa", "Masa Pelaksanaan", "text", "Contoh: 8.00 pagi – 12.00 tengah hari"], ["penglibatan", "Penglibatan *", "text", "Contoh: 80 murid Tahun 6", true], ["lokasi", "Lokasi *", "text", "Contoh: Dewan sekolah", true], ["pelibatan", "Pihak luar / Kerjasama", "text", "Jika ada"], ["objektif", "Objektif Program *", "textarea", "1. …", true, "objektif"], ["kekuatan", "Kekuatan Program *", "textarea", "• …", true, "kekuatan"], ["penambahbaikan", "Penambahbaikan & Cadangan *", "textarea", "• …", true, "penambahbaikan"] ] },
  perancangan: { title: "OPR Perancangan", description: "Perancangan teratur sebelum program dilaksanakan.", fields: [
    ["tajukProgram", "Tajuk Program / Aktiviti *", "text", "Contoh: Program…", true], ["tarikhPelaksanaan", "Tarikh Pelaksanaan *", "text", "Contoh: 12 Ogos 2026", true], ["penglibatan", "Penglibatan *", "text", "Contoh: Guru dan murid", true], ["lokasi", "Lokasi *", "text", "Contoh: Dewan sekolah", true], ["senaraiAjk", "Senarai AJK", "textarea", "Pengerusi: …", false, "ajk"], ["objektif", "Objektif *", "textarea", "1. …", true, "objektif"], ["sumberKewangan", "Sumber Kewangan", "text", "Contoh: PCG / PIBG"], ["outputProgram", "Output Program", "textarea", "• …", false, "output"] ] },
  pelaksanaan: { title: "OPR Pelaksanaan", description: "Catatan pelaksanaan program dan penglibatan sebenar.", fields: [
    ["tajukProgram", "Tajuk Program / Aktiviti *", "text", "Contoh: Program…", true], ["tarikhPelaksanaan", "Tarikh / Tempoh Pelaksanaan *", "text", "Contoh: 12–14 Ogos 2026", true], ["lokasi", "Lokasi *", "text", "Contoh: Dewan sekolah", true], ["penglibatan", "Penglibatan *", "text", "Contoh: 80 murid Tahun 6", true], ["perincianProgram", "Perincian Program *", "textarea", "• …", true, "perincian"] ] },
  pemantauan: { title: "OPR Pemantauan & Penilaian", description: "Menilai hasil program, kekangan dan tindakan penambahbaikan.", fields: [
    ["tajukProgram", "Tajuk Program / Aktiviti *", "text", "Contoh: Program…", true], ["tarikhPelaksanaan", "Tarikh / Tempoh Pelaksanaan *", "text", "Contoh: 12–14 Ogos 2026", true], ["penglibatan", "Penglibatan *", "text", "Contoh: 80 murid Tahun 6", true], ["lokasi", "Lokasi *", "text", "Contoh: Dewan sekolah", true], ["senaraiAjk", "Senarai AJK", "textarea", "Pengerusi: …", false, "ajk"], ["outputProgram", "Output Program", "textarea", "• …", false, "output"], ["kekanganProgram", "Kekangan Program", "textarea", "• …"], ["penambahbaikan", "Cadangan & Penambahbaikan", "textarea", "• …", false, "penambahbaikan"] ] },
  susulan: { title: "OPR Tindakan Susulan", description: "Merekod tindakan lanjutan dan hasil yang disasarkan.", fields: [
    ["tajukProgram", "Tajuk Program / Aktiviti *", "text", "Contoh: Program…", true], ["tarikhPelaksanaan", "Tarikh / Tempoh Pelaksanaan *", "text", "Contoh: 12–14 Ogos 2026", true], ["penglibatan", "Penglibatan *", "text", "Contoh: 80 murid Tahun 6", true], ["lokasi", "Lokasi *", "text", "Contoh: Dewan sekolah", true], ["senaraiAjk", "Senarai AJK", "textarea", "Pengerusi: …", false, "ajk"], ["penambahbaikan", "Cadangan & Penambahbaikan", "textarea", "• …", false, "penambahbaikan"], ["outputProgram", "Output Program", "textarea", "• …", false, "output"] ] }
};
const SUGGESTIONS = {
  ajk: "Pengerusi: Rozani binti Muri\nNaib Pengerusi: Harsharanjit Kaur a/p Tejinder Singh\nPenyelaras: \nAJK: ",
  objektif: "1. Meningkatkan kefahaman dan penglibatan peserta dalam program yang dilaksanakan.\n2. Memperkukuh kerjasama serta pelaksanaan aktiviti secara terancang.\n3. Memastikan hasil program dapat dimanfaatkan oleh kumpulan sasaran.",
  kekuatan: "• Penglibatan aktif peserta sepanjang program.\n• Kerjasama baik daripada jawatankuasa pelaksana.\n• Pengisian program tersusun dan menepati objektif.",
  penambahbaikan: "• Memperkemas hebahan awal kepada semua peserta.\n• Menambah baik pengurusan masa dan dokumentasi program.",
  output: "• Program dilaksanakan mengikut perancangan.\n• Peserta mendapat manfaat daripada pengisian yang disampaikan.\n• Dokumentasi dan tindakan susulan disediakan.",
  perincian: "• Pendaftaran dan taklimat peserta.\n• Pelaksanaan aktiviti utama mengikut atur cara.\n• Refleksi dan rumusan program bersama peserta."
};
const state = { field:"", type:"umum", photos:{}, changedPhotos:{}, removedPhotos:[], heroX:50, heroY:50, records:[], officers:[], editId:"", draftTimer:null, archiveView:"pegawai", imageSources:{} };
let cropperInstance=null, activeImageIndex=null;
const $ = (s) => document.querySelector(s);
const escapeHtml = (s="") => String(s).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));

document.addEventListener("DOMContentLoaded", () => {
  $("[name=tarikhLaporan]").value = new Date().toISOString().slice(0,10);
  $("#month-label").textContent = new Intl.DateTimeFormat("ms-MY",{month:"long",year:"numeric"}).format(new Date());
  bindEvents(); loadRecords(); window.addEventListener("resize",fitPreview);
});
function bindEvents(){
  document.querySelectorAll("[data-nav]").forEach(x=>x.addEventListener("click",()=>navigate(x.dataset.nav)));
  $(".menu-button")?.addEventListener("click",()=>$(".topbar nav").classList.toggle("open"));
  $("#new-opr").addEventListener("click",()=>navigate("new"));
  document.querySelectorAll(".field-card").forEach(x=>x.addEventListener("click",()=>chooseField(x.dataset.field)));
  $("#form-back").addEventListener("click",()=>chooseField(state.field));
  $("#opr-form").addEventListener("input",()=>{renderPreview();queueDraft();});
  $("#opr-form").addEventListener("keydown",handleStructuredKey);
  $("[name=namaPegawai]").addEventListener("input",filterOfficers);
  $("[name=namaPegawai]").addEventListener("focus",filterOfficers);
  $("[name=namaPegawai]").addEventListener("blur",()=>setTimeout(()=>$("#officer-options").hidden=true,150));
  $("#reset-form").addEventListener("click",resetForm);
  $("#submit-opr").addEventListener("click",submitRecord);
  $("#download-preview").addEventListener("click",()=>createPdf(true));
  document.querySelectorAll("input[data-image]").forEach(x=>x.addEventListener("change",readImage));
  document.querySelectorAll("[data-remove-photo]").forEach(x=>x.addEventListener("click",()=>removePhoto(x.dataset.removePhoto)));
  document.querySelectorAll("[data-edit-photo]").forEach(x=>x.addEventListener("click",()=>openImageEditor(x.dataset.editPhoto)));
  $("#close-image-editor").addEventListener("click",closeImageEditor); $("#crop-cancel").addEventListener("click",closeImageEditor); $("#crop-reset").addEventListener("click",()=>cropperInstance?.reset()); $("#crop-apply").addEventListener("click",applyImageCrop); $("#close-save-progress").addEventListener("click",closeSaveProgress);
  $("#archive-search").addEventListener("input",renderArchive); $("#archive-field").addEventListener("change",renderArchive); $("#archive-date").addEventListener("change",renderArchive);
  document.querySelectorAll("[data-archive-view]").forEach(b=>b.addEventListener("click",()=>{state.archiveView=b.dataset.archiveView;document.querySelectorAll("[data-archive-view]").forEach(x=>x.classList.toggle("active",x===b));renderArchive()}));
  $("#close-dialog").addEventListener("click",()=>$("#status-dialog").close());
}
function navigate(target){
  if(target==="new"){ state.editId=""; state.field=""; $("#edit-banner").hidden=true; $("#type-heading").textContent="Pilih bidang"; $("#type-lede").textContent="Pilih bidang untuk memulakan OPR baharu."; $("#type-grid").innerHTML=""; ["Pentadbiran","Kurikulum","Hal Ehwal Murid","Kokurikulum"].forEach(f=>$("#type-grid").append(typeCard(f,"Pilih bidang ini untuk meneruskan.",()=>chooseField(f)))); show("type"); return; }
  show(target); if(target==="archive")renderArchive();
}
function show(id){document.querySelectorAll(".view").forEach(v=>v.classList.remove("active")); $("#"+id+"-view").classList.add("active");document.querySelectorAll(".nav-link").forEach(b=>b.classList.toggle("active",b.dataset.nav===id|| (id==="type"&&b.dataset.nav==="new")));window.scrollTo({top:0,behavior:"smooth"});}
function chooseField(field){ state.field=field; $("#selected-field-label").textContent=field.toUpperCase(); if(field!=="Kurikulum"){selectType("umum");return;} $("#type-heading").textContent="Pilih jenis OPR"; $("#type-lede").textContent="Bidang Kurikulum mempunyai lima format laporan."; $("#type-grid").innerHTML=""; Object.entries(FORM_TYPES).forEach(([key,item])=>$("#type-grid").append(typeCard(item.title,item.description,()=>selectType(key))));show("type");}
function typeCard(title,desc,onClick){const b=document.createElement("button");b.className="type-card";b.innerHTML=`<strong>${escapeHtml(title)}</strong><span>${escapeHtml(desc)}</span><p>Teruskan →</p>`;b.addEventListener("click",onClick);return b;}
function selectType(type){state.type=type;state.photos={};state.changedPhotos={};state.removedPhotos=[];state.imageSources={};state.heroX=50;state.heroY=50;$("#opr-form").reset();$("[name=tarikhLaporan]").value=new Date().toISOString().slice(0,10);$("#form-field-label").textContent=state.field.toUpperCase()+" · "+FORM_TYPES[type].title.toUpperCase();$("#form-title").textContent=FORM_TYPES[type].title;renderFields();renderPreview();show("form");}
function renderFields(){const area=$("#dynamic-fields");area.innerHTML="";FORM_TYPES[state.type].fields.forEach(([name,label,type,placeholder,required,suggestion])=>{const wrap=document.createElement("div");wrap.className=type==="textarea"?"wide":"";const lab=document.createElement("label");lab.textContent=label;const input=document.createElement(type==="textarea"?"textarea":"input");input.name=name;input.type=type==="textarea"?"text":type;input.placeholder=placeholder||"";input.required=!!required;lab.append(input);wrap.append(lab);if(suggestion){const tools=document.createElement("div");tools.className="field-tools";const b=document.createElement("button");b.type="button";b.textContent="Cadangan";b.addEventListener("click",()=>{input.value=randomSuggestion(suggestion);input.focus();renderPreview()});const c=document.createElement("button");c.type="button";c.textContent="Kosongkan";c.addEventListener("click",()=>{input.value="";input.focus();renderPreview()});tools.append(b,c);wrap.append(tools)}area.append(wrap)});}
function formData(){const data={bidang:state.field,jenisOpr:state.type,rowId:state.editId||"",heroPosition:{x:state.heroX,y:state.heroY}};new FormData($("#opr-form")).forEach((v,k)=>data[k]=v);return data;}
function labelFor(name){const f=FORM_TYPES[state.type].fields.find(x=>x[0]===name);return f?f[1].replace(/\s*\*.*/,""):name;}
function renderPreview(){if(!state.field)return;const d=formData(), type=FORM_TYPES[state.type], metaNames=["tajukProgram","tarikhPelaksanaan","penglibatan","lokasi","masa"],title=escapeHtml(d.tajukProgram||"TAJUK PROGRAM / AKTIVITI");const meta=[["TARIKH",d.tarikhPelaksanaan],["PENGLIBATAN",d.penglibatan],["LOKASI",d.lokasi]];if(state.type==="umum"&&d.masa)meta.splice(1,0,["MASA",d.masa]);const sections=FORM_TYPES[state.type].fields.filter(x=>!metaNames.includes(x[0])).map(x=>`<div class="pdf-section"><b>${escapeHtml(labelFor(x[0]).toUpperCase())}</b><p>${escapeHtml(d[x[0]]||"—")}</p></div>`).join("");const hero=state.photos[1]?`<div class="pdf-hero" id="hero-preview"><img src="${state.photos[1]}" style="object-position:${state.heroX}% ${state.heroY}%"><div class="pdf-hero-title">${title}</div></div>`:`<div class="pdf-program">${title}</div>`;const gallery=[2,3,4].filter(i=>state.photos[i]).map(i=>`<img src="${state.photos[i]}" alt="Gambar program">`).join("");$("#opr-preview").innerHTML=`<div class="pdf-head"><img src="assets/logo-mps.png" alt=""><div class="pdf-title"><strong>LAPORAN RINGKAS PROGRAM / AKTIVITI</strong><span>SK METHODIST PJ</span><div class="pdf-tag">${escapeHtml(type.title.toUpperCase())} · ${escapeHtml(state.field.toUpperCase())}</div></div><img class="jata" src="${JATA_URL}" alt="Jata Negara"></div>${hero}<div class="pdf-meta">${meta.map(m=>`<div><b>${m[0]}</b><span>${escapeHtml(m[1]||"—")}</span></div>`).join("")}</div><div class="pdf-sections">${sections||""}</div>${gallery?`<div class="pdf-gallery-box"><b>📸 LAMPIRAN BERGAMBAR</b><div class="pdf-gallery">${gallery}</div></div>`:""}<div class="pdf-sign"><span><b>Disediakan oleh:</b> ${escapeHtml(d.namaPegawai||"—")} (${escapeHtml(d.jawatanPegawai||"—")})</span><span>${escapeHtml(d.tarikhLaporan||"")}</span></div>`;bindHeroDrag();requestAnimationFrame(fitPreview);}
function fitPreview(){const panel=$(".preview-panel"),preview=$("#opr-preview");if(!panel||!preview)return;const width=panel.clientWidth||794;panel.style.setProperty("--preview-scale",Math.min(1,width/794));}
function bindHeroDrag(){const h=$("#hero-preview");if(!h)return;let start;h.onpointerdown=e=>{start={x:e.clientX,y:e.clientY,px:+state.heroX,py:+state.heroY};h.setPointerCapture(e.pointerId)};h.onpointermove=e=>{if(!start)return;state.heroX=Math.max(0,Math.min(100,start.px-(e.clientX-start.x)/h.clientWidth*100));state.heroY=Math.max(0,Math.min(100,start.py-(e.clientY-start.y)/h.clientHeight*100));h.querySelector("img").style.objectPosition=`${state.heroX}% ${state.heroY}%`};h.onpointerup=()=>start=null;}
function readImage(event){const file=event.target.files[0],index=event.target.dataset.image;if(!file)return;if(!file.type.startsWith("image/")){showDialog("Fail tidak sah","Sila pilih fail gambar yang sah.");event.target.value="";return}if(file.size>15*1024*1024){showDialog("Gambar terlalu besar","Had maksimum gambar ialah 15 MB.");event.target.value="";return}state.imageSources[index]=URL.createObjectURL(file);openImageEditor(index,state.imageSources[index]);}
function openImageEditor(index,source=" "){const actual=source.trim()||state.imageSources[index]||state.photos[index];if(!actual)return;activeImageIndex=Number(index);const modal=$("#image-editor-modal"),image=$("#cropper-image");modal.hidden=false;image.src=actual;if(cropperInstance)cropperInstance.destroy();cropperInstance=new Cropper(image,{aspectRatio:activeImageIndex===1?16/9:4/3,viewMode:1,dragMode:"move",autoCropArea:1,responsive:true,background:false,guides:true,center:true,movable:true,zoomable:false,zoomOnWheel:false,zoomOnTouch:false,cropBoxMovable:false,cropBoxResizable:false,scalable:false,rotatable:false,toggleDragModeOnDblclick:false});}
function closeImageEditor(){$("#image-editor-modal").hidden=true;if(cropperInstance){cropperInstance.destroy();cropperInstance=null}activeImageIndex=null;}
function applyImageCrop(){if(!cropperInstance||!activeImageIndex)return;const index=activeImageIndex,canvas=cropperInstance.getCroppedCanvas({width:index===1?1280:900,height:index===1?720:675,imageSmoothingEnabled:true,imageSmoothingQuality:"high",fillColor:"#fff"});state.photos[index]=canvas.toDataURL("image/jpeg",.8);state.changedPhotos[index]=state.photos[index];state.removedPhotos=state.removedPhotos.filter(x=>x!==index);$("#photo-status").hidden=false;$("#photo-status").textContent=`Gambar ${index} sedia digunakan${index===1?" sebagai hero":""}.`;if(index===1)$("#hero-upload-name").textContent="Hero telah disunting";closeImageEditor();renderPreview();}
function removePhoto(index){if(!state.photos[index])return;delete state.photos[index];delete state.changedPhotos[index];if(!state.removedPhotos.includes(Number(index)))state.removedPhotos.push(Number(index));if(String(index)==="1")$("#hero-upload-name").textContent="Pilih gambar";$("#photo-status").hidden=false;$("#photo-status").textContent=`Gambar ${index} akan dibuang apabila laporan disimpan.`;renderPreview();}
function compressImage(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=reject;r.onload=e=>{const img=new Image();img.onload=()=>{const max=1600,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement("canvas");canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext("2d").drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL("image/jpeg",.82))};img.onerror=reject;img.src=e.target.result};r.readAsDataURL(file)})}
function queueDraft(){clearTimeout(state.draftTimer);state.draftTimer=setTimeout(saveDraft,700)}
function saveDraft(){if(!state.field)return;localStorage.setItem("mps-opr-draft",JSON.stringify({data:formData(),photos:state.photos,type:state.type,field:state.field,savedAt:Date.now()}));}
async function createPdf(download=true){renderPreview();await new Promise(requestAnimationFrame);const area=$("#opr-preview");if(area.scrollHeight>area.clientHeight+2)throw new Error("Laporan terlalu panjang untuk satu halaman A4. Sila ringkaskan isi laporan.");const canvas=await html2canvas(area,{scale:2,useCORS:true,backgroundColor:"#fff"});const {jsPDF}=window.jspdf;const pdf=new jsPDF("p","mm","a4");pdf.addImage(canvas.toDataURL("image/jpeg",.92),"JPEG",0,0,210,297);const d=formData();const blob=pdf.output("blob");if(download)pdf.save(`OPR_${slug(d.tajukProgram||state.type)}.pdf`);return await blobToDataUrl(blob)}
function showSaveProgress(){const modal=$("#save-progress-modal");modal.hidden=false;$("#save-progress-message").hidden=true;$("#close-save-progress").hidden=true;document.querySelectorAll("[data-step]").forEach(x=>x.className="");}
function setSaveStep(step,status){const el=document.querySelector(`[data-step="${step}"]`);if(el)el.className=status;}
function closeSaveProgress(){$("#save-progress-modal").hidden=true;}
function progressError(step,message){setSaveStep(step,"error");const box=$("#save-progress-message");box.textContent=message;box.hidden=false;$("#close-save-progress").hidden=false;}
async function submitRecord(){if(!$("#opr-form").reportValidity())return;const btn=$("#submit-opr");btn.disabled=true;btn.textContent="Menyediakan laporan…";showSaveProgress();let step="images";try{setSaveStep("images","active");await new Promise(requestAnimationFrame);setSaveStep("images","done");step="pdf";setSaveStep("pdf","active");const pdfBase64=await createPdf(false);setSaveStep("pdf","done");step="drive";setSaveStep("drive","active");const payload={record:formData(),photos:state.changedPhotos,removedPhotos:state.removedPhotos,pdfBase64},res=await fetch(GAS_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(payload)}),result=await res.json();if(result.status!=="success")throw new Error(result.message);setSaveStep("drive","done");state.editId=result.rowId;state.changedPhotos={};state.removedPhotos=[];await loadRecords();$("#edit-banner").hidden=false;setSaveStep("done","done");$("#close-save-progress").hidden=false}catch(err){progressError(step,err.message||"Sila cuba lagi.")}finally{btn.disabled=false;btn.textContent="Simpan laporan & jana PDF"}}
function blobToDataUrl(blob){return new Promise(resolve=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.readAsDataURL(blob)})}function slug(s){return String(s).replace(/[^a-z0-9]+/gi,"_").replace(/^_|_$/g,"").slice(0,50)}
async function loadRecords(){try{const res=await fetch(GAS_URL+"?action=getInitialData"),data=await res.json();if(data.status!=="success")throw new Error(data.message);state.records=data.records||[];state.officers=data.officers||[];}catch(e){console.warn(e);state.records=[];state.officers=[]}renderHome();renderArchive()}
function renderHome(){const rows=state.records.slice().sort((a,b)=>String(b.timestamp||"").localeCompare(String(a.timestamp||"")));$("#stat-total").textContent=rows.length;const month=new Date().toISOString().slice(0,7);$("#stat-month").textContent=rows.filter(r=>String(r.timestamp||"").startsWith(month)).length;$("#recent-list").innerHTML=rows.slice(0,4).map(r=>`<div class="recent-row"><div><strong>${escapeHtml(r.tajukProgram||"Tanpa tajuk")}</strong><small>${escapeHtml(r.bidang||"")} · ${escapeHtml(r.namaPegawai||"")}</small></div><button class="text-button" data-edit="${escapeHtml(r.rowId)}">Buka →</button></div>`).join("")||"<p class=\"empty-state\">Belum ada OPR direkodkan.</p>";bindEdit();}
function renderArchive(){const q=$("#archive-search")?.value?.toLowerCase()||"",field=$("#archive-field")?.value||"",date=$("#archive-date")?.value||"",rows=state.records.filter(r=>(!field||r.bidang===field)&&(!date||String(r.timestamp||"").includes(date))&&(`${r.tajukProgram||""} ${r.namaPegawai||""}`).toLowerCase().includes(q)),key=state.archiveView==="pegawai"?"namaPegawai":"bidang",groups={};rows.forEach(r=>(groups[r[key]||"Tidak dinyatakan"]??=[]).push(r));$("#archive-list").innerHTML=Object.entries(groups).map(([name,list])=>`<section class="archive-group"><h2>${escapeHtml(name)} <small>${list.length} rekod</small></h2>${list.map(r=>`<div class="archive-row"><small>${new Date(r.timestamp||Date.now()).toLocaleDateString("ms-MY")}</small><div><strong>${escapeHtml(r.tajukProgram||"Tanpa tajuk")}</strong><small>${escapeHtml(r.namaPegawai||"")} · ${escapeHtml(FORM_TYPES[r.jenisOpr]?.title||"OPR Umum")}</small></div><span class="badge">${escapeHtml(r.bidang||"")}</span><div class="archive-actions">${r.pdfUrl?`<a href="${escapeHtml(r.pdfUrl)}" target="_blank" rel="noopener">PDF</a>`:""}<button data-edit="${escapeHtml(r.rowId)}">Edit</button></div></div>`).join("")}</section>`).join("")||"<p class=\"empty-state\">Tiada rekod sepadan.</p>";bindEdit();}
function bindEdit(){document.querySelectorAll("[data-edit]").forEach(b=>b.addEventListener("click",()=>editRecord(b.dataset.edit)));}
async function editRecord(id){const button=document.querySelector(`[data-edit="${id}"]`);if(button){button.disabled=true;button.textContent="Membuka…"}try{const res=await fetch(GAS_URL+"?action=getRecord&rowId="+encodeURIComponent(id)),data=await res.json();if(data.status!=="success"||!data.record)throw Error(data.message||"Rekod tidak ditemui.");const r=data.record;state.field=r.bidang;state.type=r.jenisOpr||"umum";state.editId=r.rowId;selectType(state.type);Object.entries(r).forEach(([k,v])=>{const el=$(`[name="${k}"]`);if(el)el.value=v||""});state.photos={};(data.photos||[]).forEach((image,i)=>{if(image)state.photos[i+1]=image});state.changedPhotos={};state.removedPhotos=[];state.heroX=r.heroPosition?.x===""||r.heroPosition?.x===undefined?50:Number(r.heroPosition.x);state.heroY=r.heroPosition?.y===""||r.heroPosition?.y===undefined?50:Number(r.heroPosition.y);$("#photo-status").hidden=!state.photos[1];$("#edit-banner").hidden=false;renderPreview()}catch(error){showDialog("Rekod tidak dapat dibuka",error.message||"Sila cuba lagi.")}finally{if(button){button.disabled=false;button.textContent="Edit"}}}
function filterOfficers(){const q=$("[name=namaPegawai]").value.toLowerCase(),box=$("#officer-options"),list=state.officers.filter(p=>`${p.nama} ${p.jawatan}`.toLowerCase().includes(q)).slice(0,12);box.innerHTML=list.map((p,i)=>`<button type="button" data-officer="${i}"><strong>${escapeHtml(p.nama)}</strong><small>${escapeHtml(p.jawatan||"")}</small></button>`).join("")||"<p>Tiada pegawai sepadan.</p>";box.hidden=false;box.querySelectorAll("button").forEach((b,i)=>b.onclick=()=>selectOfficer(list[i]));}
function selectOfficer(p){$("[name=namaPegawai]").value=p.nama;$("[name=jawatanPegawai]").value=p.jawatan||"";$("#officer-options").hidden=true;renderPreview();}
function resetForm(){if(!confirm("Kosongkan semua maklumat dalam borang ini?"))return;state.photos={};state.changedPhotos={};state.removedPhotos=[];state.editId="";$("#edit-banner").hidden=true;$("#opr-form").reset();$("[name=tarikhLaporan]").value=new Date().toISOString().slice(0,10);$("#photo-status").hidden=true;$("#hero-upload-name").textContent="Pilih gambar";renderPreview();}
function randomSuggestion(type){const base=SUGGESTIONS[type]||"";const alternatives={objektif:[base,"1. Meningkatkan keupayaan peserta dalam pelaksanaan program.\n2. Mengukuhkan kerjasama antara pihak berkaitan.\n3. Memastikan hasil program memberi impak kepada sasaran."],kekuatan:[base,"• Komitmen tinggi jawatankuasa dan peserta.\n• Pengurusan program mengikut perancangan.\n• Suasana pelaksanaan kondusif dan berkesan."],penambahbaikan:[base,"• Menyediakan hebahan lebih awal.\n• Memperkemas instrumen maklum balas dan dokumentasi."],output:[base,"• Sasaran program menerima input yang diperlukan.\n• Laporan dan dokumentasi disimpan untuk tindakan susulan."],perincian:[base,"• Taklimat awal dan pembahagian peranan.\n• Aktiviti utama dilaksanakan secara berfasa.\n• Rumusan serta tindakan susulan direkodkan."]};const items=alternatives[type]||[base];return items[Math.floor(Math.random()*items.length)]}
function handleStructuredKey(e){const el=e.target;if(el.tagName!=="TEXTAREA")return;const kind=el.name==="objektif"?"number":(["kekuatan","penambahbaikan","outputProgram","perincianProgram","kekanganProgram"].includes(el.name)?"bullet":"");if(!kind||e.key!=="Enter"||e.shiftKey)return;e.preventDefault();const line=el.value.slice(0,el.selectionStart).split("\n").pop();const prefix=kind==="number"?`${Number((line.match(/^(\d+)\./)||[,0])[1])+1||1}. `:"• ";el.setRangeText(`\n${prefix}`,el.selectionStart,el.selectionEnd,"end");renderPreview()}
function showDialog(title,message){$("#status-content").innerHTML=`<h2>${escapeHtml(title)}</h2><p>${escapeHtml(message)}</p>`;$("#status-dialog").showModal();}
