/* Set the Apps Script deployment URL after deploying apps-script/Code.gs. */
const GAS_URL = "https://script.google.com/macros/s/AKfycbyhPN_YBVpTp_fKne4BAlxIkyBA9wtT3QjIFkAsi-ZxX6m69IkUlw3KeRgzfG-xy6-vbQ/exec";
const JATA_URL = "https://i.ibb.co/fYY58Rh2/JATA-NEGARA-PNG.png";
const FORM_TYPES = {
  umum: { title: "OPR Umum", description: "Laporan program lengkap dengan objektif, kekuatan dan penambahbaikan.", fields: [
    ["tajukProgram", "Tajuk Program / Aktiviti *", "text", "Contoh: Program…", true], ["tarikhPelaksanaan", "Tarikh / Tempoh Pelaksanaan *", "text", "Contoh: 12 Ogos 2026", true], ["masa", "Masa Pelaksanaan", "text", "Contoh: 8.00 pagi – 12.00 tengah hari"], ["penglibatan", "Penglibatan *", "text", "Contoh: 80 murid Tahun 6", true], ["lokasi", "Lokasi *", "text", "Contoh: Dewan sekolah", true], ["pelibatan", "Pihak luar / Kerjasama", "text", "Jika ada"], ["objektif", "Objektif Program *", "textarea", "1. …", true, "objektif"], ["kekuatan", "Kekuatan Program *", "textarea", "• …", true, "kekuatan"], ["penambahbaikan", "Penambahbaikan & Cadangan *", "textarea", "• …", true, "penambahbaikan"] ] },
  perancangan: { title: "OPR Perancangan", description: "Perancangan teratur sebelum program dilaksanakan.", fields: [
    ["tajukProgram", "Tajuk Program / Aktiviti *", "text", "Contoh: Program…", true], ["tarikhPelaksanaan", "Tarikh Pelaksanaan *", "text", "Contoh: 12 Ogos 2026", true], ["penglibatan", "Penglibatan *", "text", "Contoh: Guru dan murid", true], ["lokasi", "Lokasi *", "text", "Contoh: Dewan sekolah", true], ["senaraiAjk", "Senarai AJK", "textarea", "Pengerusi: …", false, "ajk"], ["objektif", "Objektif *", "textarea", "1. …", true, "objektif"], ["sumberKewangan", "Sumber Kewangan", "text", "Contoh: PCG / PIBG"], ["outputProgram", "Output Program", "textarea", "• …", false, "output"] ] },
  pelaksanaan: { title: "OPR Pelaksanaan", description: "Catatan pelaksanaan program dan penglibatan sebenar.", fields: [
    ["tajukProgram", "Tajuk Program / Aktiviti *", "text", "Contoh: Program…", true], ["tarikhPelaksanaan", "Tarikh / Tempoh Pelaksanaan *", "text", "Contoh: 12–14 Ogos 2026", true], ["lokasi", "Lokasi *", "text", "Contoh: Dewan sekolah", true], ["penglibatan", "Penglibatan *", "text", "Contoh: 80 murid Tahun 6", true], ["perincianProgram", "Perincian Program *", "textarea", "• …", true, "perincian"] ] },
  pemantauan: { title: "OPR Pemantauan & Penilaian", description: "Menilai hasil program, kekangan dan tindakan penambahbaikan.", fields: [
    ["tajukProgram", "Tajuk Program / Aktiviti *", "text", "Contoh: Program…", true], ["tarikhPelaksanaan", "Tarikh / Tempoh Pelaksanaan *", "text", "Contoh: 12–14 Ogos 2026", true], ["penglibatan", "Penglibatan *", "text", "Contoh: 80 murid Tahun 6", true], ["lokasi", "Lokasi *", "text", "Contoh: Dewan sekolah", true], ["senaraiAjk", "Senarai AJK", "textarea", "Pengerusi: …", false, "ajk"], ["outputProgram", "Output Program", "textarea", "• …", false, "output"], ["kekanganProgram", "Kekangan Program", "textarea", "• …"], ["penambahbaikan", "Cadangan & Penambahbaikan", "textarea", "• …", false, "penambahbaikan"] ] },
  susulan: { title: "OPR Tindakan Susulan", description: "Merekod tindakan lanjutan dan hasil yang disasarkan.", fields: [
    ["tajukProgram", "Tajuk Program / Aktiviti *", "text", "Contoh: Program…", true], ["tarikhPelaksanaan", "Tarikh / Tempoh Pelaksanaan *", "text", "Contoh: 12–14 Ogos 2026", true], ["penglibatan", "Penglibatan *", "text", "Contoh: 80 murid Tahun 6", true], ["lokasi", "Lokasi *", "text", "Contoh: Dewan sekolah", true], ["senaraiAjk", "Senarai AJK", "textarea", "Pengerusi: …", false, "ajk"], ["penambahbaikan", "Cadangan & Penambahbaikan", "textarea", "• …", false, "penambahbaikan"], ["outputProgram", "Output Program", "textarea", "• …", false, "output"] ] }
};
const SUGGESTIONS = {
  ajk: "Pengerusi: Rozani binti Muri\nNaib Pengerusi: Harsharanjit Kaur a/p Tejinder Singh\nPenyelaras: \nAJK: ",
  objektif: "1. Meningkatkan kefahaman dan penglibatan peserta dalam program yang dilaksanakan.\n2. Memperkukuh kerjasama serta pelaksanaan aktiviti secara terancang.\n3. Memastikan hasil program dapat dimanfaatkan oleh kumpulan sasaran.",
  kekuatan: "• Penglibatan aktif peserta sepanjang program.\n• Kerjasama baik daripada jawatankuasa pelaksana.\n• Pengisian program tersusun dan menepati objektif.",
  penambahbaikan: "• Memperkemas hebahan awal kepada semua peserta.\n• Menambah baik pengurusan masa dan dokumentasi program.",
  output: "• Program dilaksanakan mengikut perancangan.\n• Peserta mendapat manfaat daripada pengisian yang disampaikan.\n• Dokumentasi dan tindakan susulan disediakan.",
  perincian: "• Pendaftaran dan taklimat peserta.\n• Pelaksanaan aktiviti utama mengikut atur cara.\n• Refleksi dan rumusan program bersama peserta."
};
const state = { field:"", type:"umum", photos:{}, heroX:50, heroY:50, records:[], editId:"", draftTimer:null };
const $ = (s) => document.querySelector(s);
const escapeHtml = (s="") => String(s).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));

document.addEventListener("DOMContentLoaded", () => {
  $("[name=tarikhLaporan]").value = new Date().toISOString().slice(0,10);
  $("#month-label").textContent = new Intl.DateTimeFormat("ms-MY",{month:"long",year:"numeric"}).format(new Date());
  bindEvents(); loadRecords();
});
function bindEvents(){
  document.querySelectorAll("[data-nav]").forEach(x=>x.addEventListener("click",()=>navigate(x.dataset.nav)));
  $("#new-opr").addEventListener("click",()=>navigate("new"));
  document.querySelectorAll(".field-card").forEach(x=>x.addEventListener("click",()=>chooseField(x.dataset.field)));
  $("#form-back").addEventListener("click",()=>chooseField(state.field));
  $("#opr-form").addEventListener("input",()=>{renderPreview();queueDraft();});
  $("#save-draft").addEventListener("click",()=>saveDraft());
  $("#submit-opr").addEventListener("click",submitRecord);
  $("#download-preview").addEventListener("click",()=>createPdf(false));
  $("#hero-x").addEventListener("input",e=>{state.heroX=e.target.value;renderPreview()}); $("#hero-y").addEventListener("input",e=>{state.heroY=e.target.value;renderPreview()});
  document.querySelectorAll("input[data-image]").forEach(x=>x.addEventListener("change",readImage));
  $("#archive-search").addEventListener("input",renderArchive); $("#archive-field").addEventListener("change",renderArchive); $("#archive-date").addEventListener("change",renderArchive);
  $("#close-dialog").addEventListener("click",()=>$("#status-dialog").close());
}
function navigate(target){
  if(target==="new"){ state.editId=""; state.field=""; $("#edit-banner").hidden=true; $("#type-heading").textContent="Pilih bidang"; $("#type-lede").textContent="Pilih bidang untuk memulakan OPR baharu."; $("#type-grid").innerHTML=""; ["Pentadbiran","Kurikulum","Hal Ehwal Murid","Kokurikulum"].forEach(f=>$("#type-grid").append(typeCard(f,"Pilih bidang ini untuk meneruskan.",()=>chooseField(f)))); show("type"); return; }
  show(target); if(target==="archive")renderArchive();
}
function show(id){document.querySelectorAll(".view").forEach(v=>v.classList.remove("active")); $("#"+id+"-view").classList.add("active");document.querySelectorAll(".nav-link").forEach(b=>b.classList.toggle("active",b.dataset.nav===id|| (id==="type"&&b.dataset.nav==="new")));window.scrollTo({top:0,behavior:"smooth"});}
function chooseField(field){ state.field=field; $("#selected-field-label").textContent=field.toUpperCase(); if(field!=="Kurikulum"){selectType("umum");return;} $("#type-heading").textContent="Pilih jenis OPR"; $("#type-lede").textContent="Bidang Kurikulum mempunyai lima format laporan."; $("#type-grid").innerHTML=""; Object.entries(FORM_TYPES).forEach(([key,item])=>$("#type-grid").append(typeCard(item.title,item.description,()=>selectType(key))));show("type");}
function typeCard(title,desc,onClick){const b=document.createElement("button");b.className="type-card";b.innerHTML=`<strong>${escapeHtml(title)}</strong><span>${escapeHtml(desc)}</span><p>Teruskan →</p>`;b.addEventListener("click",onClick);return b;}
function selectType(type){state.type=type;state.photos={};state.heroX=50;state.heroY=50;$("#opr-form").reset();$("[name=tarikhLaporan]").value=new Date().toISOString().slice(0,10);$("#form-field-label").textContent=state.field.toUpperCase()+" · "+FORM_TYPES[type].title.toUpperCase();$("#form-title").textContent=FORM_TYPES[type].title;renderFields();renderPreview();show("form");}
function renderFields(){const area=$("#dynamic-fields");area.innerHTML="";FORM_TYPES[state.type].fields.forEach(([name,label,type,placeholder,required,suggestion])=>{const wrap=document.createElement("label");wrap.className=type==="textarea"?"wide suggest-wrap":"";wrap.textContent=label;const input=document.createElement(type==="textarea"?"textarea":"input");input.name=name;input.type=type==="textarea"?"text":type;input.placeholder=placeholder||"";input.required=!!required;wrap.append(input);if(suggestion){const b=document.createElement("button");b.type="button";b.className="suggest-button";b.textContent="Cadangan";b.addEventListener("click",()=>{input.value=SUGGESTIONS[suggestion];renderPreview()});wrap.append(b)}area.append(wrap)});}
function formData(){const data={bidang:state.field,jenisOpr:state.type,oprId:state.editId||"",heroPosition:{x:state.heroX,y:state.heroY}};new FormData($("#opr-form")).forEach((v,k)=>data[k]=v);return data;}
function labelFor(name){const f=FORM_TYPES[state.type].fields.find(x=>x[0]===name);return f?f[1].replace(/\s*\*.*/,""):name;}
function renderPreview(){if(!state.field)return;const d=formData(), type=FORM_TYPES[state.type];const meta=[["TARIKH",d.tarikhPelaksanaan],["PENGLIBATAN",d.penglibatan],["LOKASI",d.lokasi]];if(state.type==="umum"&&d.masa)meta.splice(1,0,["MASA",d.masa]);const sections=FORM_TYPES[state.type].fields.filter(x=>["textarea"].includes(x[2])).map(x=>`<div class="pdf-section ${x[0]==="perincianProgram"?"wide":""}"><b>${escapeHtml(labelFor(x[0]).toUpperCase())}</b><p>${escapeHtml(d[x[0]]||"—")}</p></div>`).join("");const hero=state.photos[1]?`<div class="pdf-hero"><img src="${state.photos[1]}" style="object-position:${state.heroX}% ${state.heroY}%"></div>`:"";const gallery=[2,3,4].filter(i=>state.photos[i]).map(i=>`<img src="${state.photos[i]}" alt="Gambar program">`).join("");$("#opr-preview").innerHTML=`<div class="pdf-head"><img src="assets/logo-mps.png" alt=""><div class="pdf-title"><strong>LAPORAN RINGKAS PROGRAM / AKTIVITI</strong><span>SK METHODIST PJ</span><div class="pdf-tag">${escapeHtml(type.title.toUpperCase())} · ${escapeHtml(state.field.toUpperCase())}</div></div><img class="jata" src="${JATA_URL}" alt="Jata Negara"></div><div class="pdf-program">${escapeHtml(d.tajukProgram||"TAJUK PROGRAM / AKTIVITI")}</div><div class="pdf-meta">${meta.map(m=>`<div><b>${m[0]}</b><span>${escapeHtml(m[1]||"—")}</span></div>`).join("")}</div>${hero}<div class="pdf-sections">${sections||""}</div>${gallery?`<div class="pdf-gallery">${gallery}</div>`:""}<div class="pdf-sign"><span><b>Disediakan oleh:</b> ${escapeHtml(d.namaPegawai||"—")} (${escapeHtml(d.jawatanPegawai||"—")})</span><span>${escapeHtml(d.tarikhLaporan||"")}</span></div>`;}
function readImage(event){const file=event.target.files[0],index=event.target.dataset.image;if(!file)return;const reader=new FileReader();reader.onload=e=>{state.photos[index]=e.target.result;if(index==1){$("#hero-position").hidden=false;$("#hero-upload-name").textContent=file.name}renderPreview()};reader.readAsDataURL(file)}
function queueDraft(){clearTimeout(state.draftTimer);state.draftTimer=setTimeout(saveDraft,700)}
function saveDraft(){if(!state.field)return;localStorage.setItem("mps-opr-draft",JSON.stringify({data:formData(),photos:state.photos,type:state.type,field:state.field,savedAt:Date.now()}));}
async function createPdf(download=true){renderPreview();const canvas=await html2canvas($("#opr-preview"),{scale:2,useCORS:true,backgroundColor:"#fff"});const {jsPDF}=window.jspdf;const pdf=new jsPDF("p","mm","a4");pdf.addImage(canvas.toDataURL("image/jpeg",.92),"JPEG",0,0,210,297);const d=formData();const blob=pdf.output("blob");if(download)pdf.save(`OPR_${slug(d.tajukProgram||state.type)}.pdf`);return await blobToDataUrl(blob)}
async function submitRecord(){if(!$("#opr-form").reportValidity())return;const btn=$("#submit-opr");btn.disabled=true;btn.textContent="Menjana PDF…";try{const pdfBase64=await createPdf(false);const payload={action:"saveRecord",record:formData(),photos:state.photos,pdfBase64};if(!GAS_URL){addLocalRecord(payload.record);showDialog("Rekod sedia untuk disambungkan","Preview dan PDF telah dijana. Masukkan URL deployment Apps Script dalam app.js untuk simpan ke Google Sheet dan Drive.");return;}const res=await fetch(GAS_URL,{method:"POST",body:JSON.stringify(payload)});const result=await res.json();if(result.status!=="success")throw new Error(result.message);state.editId=result.oprId;await loadRecords();showDialog("OPR berjaya disimpan",`PDF telah disusun dalam folder ${state.field}.`)}catch(err){showDialog("Simpanan tidak berjaya",err.message||"Sila cuba lagi.")}finally{btn.disabled=false;btn.textContent="Simpan & jana PDF"}}
function blobToDataUrl(blob){return new Promise(resolve=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.readAsDataURL(blob)})}function slug(s){return String(s).replace(/[^a-z0-9]+/gi,"_").replace(/^_|_$/g,"").slice(0,50)}
async function loadRecords(){try{if(!GAS_URL){state.records=JSON.parse(localStorage.getItem("mps-opr-records")||"[]")}else{const res=await fetch(GAS_URL+"?action=getInitialData");const data=await res.json();state.records=data.records||[];}renderHome();renderArchive()}catch(e){console.warn(e);state.records=[];renderHome();}}
function addLocalRecord(record){const rows=JSON.parse(localStorage.getItem("mps-opr-records")||"[]");const id=record.oprId||`OPR-${Date.now()}`;const r={...record,oprId:id,timestamp:new Date().toISOString()};const old=rows.findIndex(x=>x.oprId===id);old>=0?rows.splice(old,1,r):rows.unshift(r);localStorage.setItem("mps-opr-records",JSON.stringify(rows));state.records=rows;state.editId=id;renderHome()}
function renderHome(){const rows=state.records.slice().sort((a,b)=>String(b.timestamp||"").localeCompare(String(a.timestamp||"")));$("#stat-total").textContent=rows.length;const month=new Date().toISOString().slice(0,7);$("#stat-month").textContent=rows.filter(r=>String(r.timestamp||"").startsWith(month)).length;$("#recent-list").innerHTML=rows.slice(0,4).map(r=>`<div class="recent-row"><div><strong>${escapeHtml(r.tajukProgram||"Tanpa tajuk")}</strong><small>${escapeHtml(r.bidang||"")} · ${escapeHtml(r.namaPegawai||"")}</small></div><button class="text-button" data-edit="${escapeHtml(r.oprId)}">Buka →</button></div>`).join("")||"<p class=\"empty-state\">Belum ada OPR direkodkan.</p>";document.querySelectorAll("[data-edit]").forEach(b=>b.addEventListener("click",()=>editRecord(b.dataset.edit)));}
function renderArchive(){const q=$("#archive-search")?.value?.toLowerCase()||"",field=$("#archive-field")?.value||"",date=$("#archive-date")?.value||"";const rows=state.records.filter(r=>(!field||r.bidang===field)&&(!date||String(r.timestamp||"").startsWith(date))&&(`${r.tajukProgram||""} ${r.namaPegawai||""}`).toLowerCase().includes(q));$("#archive-list").innerHTML=rows.map(r=>`<div class="archive-row"><small>${new Date(r.timestamp||Date.now()).toLocaleDateString("ms-MY")}</small><div><strong>${escapeHtml(r.tajukProgram||"Tanpa tajuk")}</strong><small>${escapeHtml(r.namaPegawai||"")} · ${escapeHtml(r.jenisOpr||"umum")}</small></div><span class="badge">${escapeHtml(r.bidang||"")}</span><button data-edit="${escapeHtml(r.oprId)}">Edit / cetak</button></div>`).join("")||"<p class=\"empty-state\">Tiada rekod sepadan.</p>";document.querySelectorAll("[data-edit]").forEach(b=>b.addEventListener("click",()=>editRecord(b.dataset.edit)));}
function editRecord(id){const r=state.records.find(x=>x.oprId===id);if(!r)return;state.field=r.bidang;state.type=r.jenisOpr||"umum";state.editId=id;selectType(state.type);Object.entries(r).forEach(([k,v])=>{const el=$(`[name="${k}"]`);if(el)el.value=v||""});state.heroX=r.heroPosition?.x||50;state.heroY=r.heroPosition?.y||50;$("#hero-x").value=state.heroX;$("#hero-y").value=state.heroY;$("#edit-banner").hidden=false;renderPreview();}
function showDialog(title,message){$("#status-content").innerHTML=`<h2>${escapeHtml(title)}</h2><p>${escapeHtml(message)}</p>`;$("#status-dialog").showModal();}
