const CONFIG={spreadsheetId:'11tnkDyYjkUsY7e388MJQ-hw-3MynBD0fkxdPAYPxLHc',responseSheet:'RESPONDOPR',officerSheet:'PEGAWAI',imageRootId:'17TOx9gmvcfkRfWa68xSv3jzp3LWwBoH-',pdfFolders:{'Pentadbiran':'1EcohzMJuDGD75ltR9--yd9cN9l5U_KhP','Kurikulum':'1-XwwFjkBr8FDwuG8VtyQZFvvUo6wTiYV','Hal Ehwal Murid':'106p3fbJ35Yv0q6poWWd2N9Leg4LYYQil','Kokurikulum':'1t8ewL_qSGNxC_iwaYLYspUgeHsmq0lwR'}};
const NEEDED=['Timestamp','Bidang','Tajuk Program','Tarikh Pelaksanaan','Masa','Penglibatan','Pelibatan','Objektif Program','Kekuatan','Penambahbaikan','Gambar 1','Kapsyen Gambar 1','Gambar 2','Kapsyen Gambar 2','Gambar 3','Kapsyen Gambar 3','Gambar 4','Kapsyen Gambar 4','Lokasi','Senarai AJK','Sumber Kewangan','Output Program','Perincian Program','Kekangan Program','Nama Pegawai Pelapor','Jawatan Pegawai','Tarikh Laporan','Pautan PDF','Jenis OPR'];
function doGet(e){try{const a=e?.parameter?.action||'';if(a==='getInitialData')return out({status:'success',records:records(),officers:officers()});if(a==='getRecord')return out({status:'success',record:records().find(x=>x.rowId==e.parameter.rowId)||null});return out({status:'success',message:'OPR MPS aktif'});}catch(x){return out({status:'error',message:x.message});}}
function doPost(e){let l;try{const p=JSON.parse(e.postData.contents);l=LockService.getScriptLock();if(!l.tryLock(30000))throw Error('Sistem sedang menyimpan laporan lain.');return out(save(p));}catch(x){return out({status:'error',message:x.message});}finally{if(l&&l.hasLock())l.releaseLock();}}
function sh(){const s=SpreadsheetApp.openById(CONFIG.spreadsheetId).getSheetByName(CONFIG.responseSheet);if(!s)throw Error('RESPONDOPR tidak ditemui');let h=head(s),i=h.indexOf('Sasaran');if(i>=0){s.getRange(1,i+1).setValue('Penglibatan');h[i]='Penglibatan';}NEEDED.forEach(x=>{if(!h.includes(x)){s.getRange(1,h.length+1).setValue(x);h.push(x);}});return s;}
function head(s){return s.getRange(1,1,1,Math.max(s.getLastColumn(),1)).getValues()[0].map(String);}
function records(){const s=sh(),h=head(s);if(s.getLastRow()<2)return[];return s.getRange(2,1,s.getLastRow()-1,h.length).getValues().map((r,i)=>{const v=x=>r[h.indexOf(x)]||'';return{rowId:i+2,timestamp:v('Timestamp'),bidang:v('Bidang'),jenisOpr:v('Jenis OPR')||'umum',tajukProgram:v('Tajuk Program'),tarikhPelaksanaan:v('Tarikh Pelaksanaan'),masa:v('Masa'),penglibatan:v('Penglibatan'),pelibatan:v('Pelibatan'),objektif:v('Objektif Program'),kekuatan:v('Kekuatan'),penambahbaikan:v('Penambahbaikan'),lokasi:v('Lokasi'),senaraiAjk:v('Senarai AJK'),sumberKewangan:v('Sumber Kewangan'),outputProgram:v('Output Program'),perincianProgram:v('Perincian Program'),kekanganProgram:v('Kekangan Program'),namaPegawai:v('Nama Pegawai Pelapor'),jawatanPegawai:v('Jawatan Pegawai'),tarikhLaporan:v('Tarikh Laporan'),pdfUrl:v('Pautan PDF'),imageUrls:['Gambar 1','Gambar 2','Gambar 3','Gambar 4'].map(v).filter(String)}}).reverse();}
function officers(){const s=SpreadsheetApp.openById(CONFIG.spreadsheetId).getSheetByName(CONFIG.officerSheet),h=head(s),n=h.indexOf('NAMA'),j=h.indexOf('JAWATAN');return s.getRange(2,1,Math.max(0,s.getLastRow()-1),h.length).getValues().map(r=>({nama:r[n],jawatan:r[j]})).filter(x=>x.nama);}
function save(p){const d=p.record||{},s=sh(),h=head(s),old=Number(d.rowId)||0;if(!d.bidang||!d.tajukProgram||!d.namaPegawai)throw Error('Maklumat OPR belum lengkap.');const imgs=saveImages(p.photos||{},folder(d.bidang,old||Date.now(),d.tajukProgram)),pdf=p.pdfBase64?DriveApp.getFolderById(CONFIG.pdfFolders[d.bidang]).createFile(blob(p.pdfBase64,clean(d.tajukProgram)+'.pdf')).getUrl():d.pdfUrl||'';const map={'Timestamp':d.timestamp||new Date(),'Bidang':d.bidang,'Jenis OPR':d.jenisOpr,'Tajuk Program':d.tajukProgram,'Tarikh Pelaksanaan':d.tarikhPelaksanaan,'Masa':d.masa,'Penglibatan':d.penglibatan,'Pelibatan':d.pelibatan,'Objektif Program':d.objektif,'Kekuatan':d.kekuatan,'Penambahbaikan':d.penambahbaikan,'Lokasi':d.lokasi,'Senarai AJK':d.senaraiAjk,'Sumber Kewangan':d.sumberKewangan,'Output Program':d.outputProgram,'Perincian Program':d.perincianProgram,'Kekangan Program':d.kekanganProgram,'Nama Pegawai Pelapor':d.namaPegawai,'Jawatan Pegawai':d.jawatanPegawai,'Tarikh Laporan':d.tarikhLaporan,'Pautan PDF':pdf};['Gambar 1','Gambar 2','Gambar 3','Gambar 4'].forEach((x,i)=>map[x]=imgs[i]||d.imageUrls?.[i]||'');const row=h.map(x=>map[x]??'');const target=old>1&&old<=s.getLastRow()?old:s.getLastRow()+1;s.getRange(target,1,1,h.length).setValues([row]);return{status:'success',rowId:target,pdfUrl:pdf};}
function folder(field,id,title){const root=DriveApp.getFolderById(CONFIG.imageRootId),a=getFolder(root,clean(field));return getFolder(a,id+'_'+clean(title));}function getFolder(p,n){const x=p.getFoldersByName(n);return x.hasNext()?x.next():p.createFolder(n);}function saveImages(x,f){return[1,2,3,4].map(i=>x[i]?f.createFile(blob(x[i],'gambar-'+i+'.jpg')).getUrl():'');}function blob(s,n){const p=String(s).split(',');return Utilities.newBlob(Utilities.base64Decode(p[1]),(p[0].match(/data:(.*?);base64/)||[,'image/jpeg'])[1],n);}function clean(s){return String(s||'OPR').replace(/[\\/:*?"<>|]/g,'').slice(0,80);}function out(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON);}
